### ISSUE TITLE
Doesn't work when applied to new project

### ISSUE THREAD

**Issue by mherb204** [CJRobertson/HTCViveTemplate-UE4#1]
The pick up and dropping of physics cube works within the project you made but when taking that setup and applying it to my project with no variance, there is no pickup ability. I'm completely lost!  This is far past the scope of this helpful template project so I'd be willing to talk about maybe some consulting?

**Comment by CJRobertson** [comment]
Are you attempting to use your own objects or the same physics cubes?

If you are trying to pick-up your own custom objects then it's mostly due to how you have those setup. The Pickup Interface and the related functions are setup to pick-up Static Mesh Actors. If you are trying to pick-up say a weapon that usually uses a skeletal mesh then it will not work since a Static Mesh Actor is different from a Skeletal Mesh Actor. If that's the case then you'd have to change the Object type on the Interface and a few of the functions in the VR_Character blueprint to reflect the item type you want to pick-up.
